language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: "XUWWSpmCnhSVT7xNnPbcaL1N8PuUbQVAQDJkO6StWbBjb+BJXRUW331/Yp4ANod49KuEJWNnIhVFuotGFwNvi9ZKVCTM2bUhQF8qNKk4bpCrsrN1TZdbDgHo0ZzqTlaZy5uEDI1o4yP2XIEufNl+tybbNnFP23dFIp7hiBn4VTw="
script:
  - bundle exec rake --trace spec
before_install:
  - gem update --system
  - gem --version
  - gem update bundler
